language: php
dist: trusty

php:
  - '7.3'

env:
  global:
    - TZ=Europe/Paris
    - DATABASE_URL=pgsql://postgres@127.0.0.1:5432/golfstats
    - DATABASE_SERVER_VERSION=11

cache:
  directories:
    - vendor
    - ~/.composer/cache/files
    - ~/.cache

notifications:
  email: false

addons:
  postgresql: '11'

jobs:
  include:
    - stage: test
      name: linting, phpstan & behat

stages:
  - test

before_install:
  # PostgreSQL
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1

  # PHP
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo date.timezone = Europe/Paris >> $INI
  - echo memory_limit = -1 >> $INI
  - echo session.gc_probability = 0 >> $INI
  - echo extension=apcu.so >> $INI

  # Start dev server
  - bin/console server:start

  # Behat setup conf
  - cp ./behat.yml.dist ./behat.yml

before_script:
  # PHP/Composer
  - composer install --no-interaction
  - APP_ENV=test bin/console cache:clear

  - APP_ENV=test bin/console doctrine:database:drop --force --if-exists --no-interaction
  - bin/console doctrine:database:create --no-interaction
  - bin/console doctrine:schema:update --force --no-interaction
  - bin/console hautelook:fixtures:load --no-interaction

script:
  - bin/console lint:yaml config --parse-tags
  - bin/php-cs-fixer-v2.phar fix --verbose --diff --dry-run src/

  - APP_ENV=test bin/console doctrine:schema:validate
  - bin/console api:swagger:export > /dev/null # trick to check if ApiPlatform is not correctly configured
  - vendor/bin/phpstan analyse --level max src/

  - vendor/bin/behat --format progress